In [3]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
from testCases import *
from dnn_utils import sigmoid, sigmoid_backward, relu, relu_backward
from public_tests import *

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)

### Initialization

We will write two helper functions to initialize the parameters for your model:
* The first function will be used to initialize parameters for a two layer model.
* The second one generalizes this initialization process to L layers

In [4]:
# initialize the parameters of the 2-layer neural network
"""
args:
    n_x         : size of the input layer
    n_h         : size of the hidden layer
    n_y         : size of the output layer
returns:
    parameters  : python dict containing parameters (W1, b1, W2, b2)
"""

def initialize_parameters(n_x, n_h, n_y):
    np.random.seed(1)
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [5]:
parameters = initialize_parameters(3, 2, 1)

print("W1 = " + str (parameters["W1"]))
print("b1 = " + str (parameters["b1"]))
print("W2 = " + str (parameters["W2"]))
print("b2 = " + str (parameters["b2"]))

W1 = [[ 0.01624345 -0.00611756 -0.00528172]
 [-0.01072969  0.00865408 -0.02301539]]
b1 = [[0.]
 [0.]]
W2 = [[ 0.01744812 -0.00761207]]
b2 = [[0.]]


The initialization for a deeper L-layer neural netowkr is more complicated because there are more weight matrices and bias vectors.

Here's an implementation for L = 1 (one layer neural network). It should inspire you to implement the general case.

if L == 1:

    parameters["W" + str(L)] = np.random.randn(layer_dims[1], layer_dims[0]) * 0.01
    
    parameters["b" + str(L)] = np.zeros((layer_dims[1], 1))

In [6]:
def initialize_parameters_deep(layer_dims):
    """
    Args:
        layer_dims      : python array (list) containing the dimensions of each layer
    returns:
        parameters 
    """
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[1], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    
    return parameters

In [7]:
parameters = initialize_parameters_deep([5, 4, 3])

print("W1 = " + str (parameters["W1"]))
print("b1 = " + str (parameters["b1"]))
print("W2 = " + str (parameters["W2"]))
print("b2 = " + str (parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]
 [-0.01244123 -0.00626417 -0.00803766 -0.02419083]]
b2 = [[0.]
 [0.]
 [0.]]


### Forward Propagation Module